### ISSUE TITLE
Code highlighter syntax not working

### ISSUE THREAD

**Issue by 33sticks** [analyticsplaybook/analyticsplaybook.github.io#2]
I struggled to get the code highlighting to work correctly, it could have just been the markdown editor I was using, but I ended up using a different syntax.

**Template Syntax**
{% highlight python %}
code block
{% endhighlight %}

**Updated Syntax**
```python
code block
```

**Comment by randyzwitch** [comment]
~~Yup, both are possible. The second (your) way is how you do it here in comments:~~

**Comment by randyzwitch** [comment]
Turns out my above comment is incorrect; you have to use the bracket-parenthesis style in the .md file, as it gets parsed by Jekyll into "GitHub-Flavored" Markdown, which I guess is not quite standard.
