### ISSUE TITLE
Left Nav Truncated

### ISSUE THREAD

**Issue by 33sticks** [analyticsplaybook/analyticsplaybook.github.io#26]
Now that the number of articles on the site has grown, the left nav appears to be truncated, I no longer am able to articles under the data visualization section.

**Comment by oarsi** [comment]
Changed the CSS to fix it

**Comment by randyzwitch** [comment]
Your changed messed something up in your article. I fixed the unicode errors, but your article doesn't render correctly (and I can't figure out why)

**Comment by oarsi** [comment]
I will have a look at it, if i am at home. Currently at the zoo.

**Comment by oarsi** [comment]
The left nav problem is fixed, and the article had the wrong template assigned.
