### ISSUE TITLE
Left Nav Flows into Article

### ISSUE THREAD

**Issue by 33sticks** [analyticsplaybook/analyticsplaybook.github.io#31]
In Chrome, the left nav is flowing into the article. This doesn't seem to be happening in Firefox.
<img width="982" alt="screen shot 2016-03-20 at 5 41 06 pm" src="https://cloud.githubusercontent.com/assets/16706503/13908170/0c1f4884-eec3-11e5-84f2-43f0ca145bd3.png">

**Comment by oarsi** [comment]
Interesting, it works well in Chrome 49 on Windows. 
![aplaybook_chrome_49_win](https://cloud.githubusercontent.com/assets/4172197/13912207/f7cc8158-ef3a-11e5-81af-41bb64d745c9.PNG)

**Comment by oarsi** [comment]
Ah, the problem is the media query respectively #menu wich is not in the media query. I will make a fix.

**Comment by oarsi** [comment]
Fixed, pull request ist done.
