### ISSUE TITLE
Switching to Jekyll blog format?

### ISSUE THREAD

**Issue by randyzwitch** [analyticsplaybook/analyticsplaybook.github.io#36]
@33sticks @oarsi Now that we're getting content, I'm wondering if the sidebar is going to become a hinderance. Or at least, thus far, there's no "You might also like..." or cross-linking between posts, no real tags (other than the category).

I think I can just steal the templates from my personal site, which auto-posts links to the sidebar; then a plugin or two and we can make finding content easier.

What do you think?

https://github.com/randyzwitch/randyzwitch.github.io

**Comment by randyzwitch** [comment]
I have the sidebar building automatically on my local machine, but need to figure out how to get the URLs to stay the same.

**Comment by randyzwitch** [comment]
Okay, sidebar automation now commited via https://github.com/analyticsplaybook/analyticsplaybook.github.io/commit/2a935709dd339c72a86bf8fa6fc1a0519e75c979. Now, all that's needed when writing is to put the post in the proper folder in the `_posts` folder and it will get posted to the sidebar. Note that all images go in the `/images/` folder now, no longer are there separate images folders.

Eventually, I'll figure out how to clean up the sidebar headings to be more elegant, and how to make the content in the main body bloggish.

**Comment by oarsi** [comment]
Let me do the clean up and blog style. I think i have an idea on how to do it

**Comment by oarsi** [comment]
Do we want a comment section under every post? i think it yould be a good idea for discussing the post

**Comment by randyzwitch** [comment]
To be honest, I'm increasingly not a fan of comments. Seems like it might be better to have them as statements, and then disagreement can happen via Twitter or pull requests.

Jason, what do you think?

**Comment by 33sticks** [comment]
I think it adds a lot of potential overhead to maintain, especially if the
site starts getting overrun by spambots.

**Comment by oarsi** [comment]
Ok, thats a good point. So building a blog format without comments.

Jason Thompson notifications@github.com schrieb am Fr., 1. Apr. 2016
17:54:

> I think it adds a lot of potential overhead to maintain, especially if the
> site starts getting overrun by spambots.
> 
> On Thu, Mar 31, 2016 at 1:25 PM, Randy Zwitch notifications@github.com
> wrote:
> 
> > To be honest, I'm increasingly not a fan of comments. Seems like it might
> > be better to have them as statements, and then disagreement can happen
> > via
> > Twitter or pull requests.
> > 
> > Jason, what do you think?
> >

**Comment by randyzwitch** [comment]
@oarsi Is there any help from me that you need to switch this over to blog format? Happy to help with whatever.

**Comment by oarsi** [comment]
@randyzwitch trying to maketo many things at once. Will upload first draft tomorrow in a new branch to show and discuss it.

**Comment by analyticsplaybook** [comment]
No hurry, we're all busy. Just wanted to offer my help if you needed it

**Comment by oarsi** [comment]
Pull request is done. Changed style, added search and tags.

**Comment by randyzwitch** [comment]
Such an improvement with the collapsing sidebar, search and tags. Definitely should be an improvement in usability and discoverability.

I'm going to make a few more changes hopefully this week, making the home page the most recent article posted and see if I can get pagination working. That will give even more opportunities for content discovery.

**Comment by ryanpraski** [comment]
@oarsi awesome updates. Just wanted to let you know when I was checking them out I noticed there was an issue with how the header displayed on mobile. (Both "Analytics Playbook" and the hamburger links.) See the screen shot below. I was using an iPhone.
![mobile_analytics_playbook_header](https://cloud.githubusercontent.com/assets/2982734/14608564/4332b3cc-0554-11e6-98b2-9dba3d5866d3.png)

**Comment by oarsi** [comment]
@ryanpraski thanks man. Updated the CSS, should now work mobile also.

**Comment by randyzwitch** [comment]
Switched front page to most recent 3 posts/added pagination.

Last thing I hope to do soon is add tag/category pages similar to this example:

http://christianspecht.de/2014/10/25/separate-pages-per-tag-category-with-jekyll-without-plugins/
