### ISSUE TITLE
Onsite Search: Yes or No?

### ISSUE THREAD

**Issue by oarsi** [analyticsplaybook/analyticsplaybook.github.io#40]
It is possible to implement a full text search with lunr.js. With hopefully more content coming up, a search would be good. Pros, Cons @randyzwitch @33sticks ?

**Comment by randyzwitch** [comment]
Absolutely! Anything that makes content easier to find, once there's too much content to quickly browse, is definitely a good idea.

**Comment by oarsi** [comment]
Ok, search is on my local dev implement, will push it with the other blog changes.

**Comment by analyticsplaybook** [comment]
Great! If you need/want any help, let me know, I have the development Jekyll server functionality set up on my computer as well.
